source 'https://rubygems.org'

gem 'bootstrap-sass', '~> 3.3.6'
gem 'coffee-rails', '~> 4.2'
gem 'faraday'
gem 'jquery-rails'
gem 'mysql2'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'sass-rails', '>= 3.2'
gem 'turbolinks'
gem 'uglifier', '>= 1.0.3'

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'listen', '~> 3.0.5'
  gem 'pry'
  gem 'rspec-rails'
end
