source 'https://rubygems.org'

gem 'rails', '3.2.22.2'
gem 'jquery-rails'
gem 'pg'
gem 'thin'
gem 'bootstrap-sass', '3.1.1.0'
gem 'sass-rails',   '~> 3.2.3'
gem 'slim'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier'
end

group :development, :test do
  gem 'pry-rails'
end
