source 'https://rubygems.org'

gem 'rails', '3.2.22.2'
gem 'jquery-rails'
gem 'pg'
gem 'thin'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
end

group :development, :test do
  gem 'pry-rails'
end
